spring.application.name=appupdater

spring.datasource.url=jdbc:postgresql://localhost:5432/updates_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

telegram.bot.name="App Updater Bot"
telegram.bot.token=8849579443:AAEwrBkBrZoy3JgdCR_qAGxe4vXLSxU4CKQ
telegram.bot.admin-chat-id=